// Realistic Beninese characters: generated by Tripo (API v3) from a description, then
// given a human skeleton (auto-rig) and animations (walking, waiting, greeting, chatting,
// phoning, sitting down…), and finally lightened for the browser. Each step is saved in
// sources/personnages/<id>.json: a network outage doesn't mean paying again for steps already done.
//   npm run personnages -- liste                 the planned characters and their status
//   npm run personnages -- <id> [<id>…]          builds these characters (or resumes where they left off)
//   npm run personnages -- tout                  builds all the missing ones
//   npm run personnages -- alleger <id>          only redoes the lightweight version
// The key is read from .env.local (TRIPO_API_KEY), never displayed.
import fs from 'fs';
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { cloneDocument, dedup, prune, textureCompress, meshopt, resample } from '@gltf-transform/functions';
import { MeshoptDecoder, MeshoptEncoder } from 'meshoptimizer';
import sharp from 'sharp';

const BASE = 'https://openapi.tripo3d.ai/v3', MODELE = 'v3.1-20260211', RIG = 'v1.0-20240301';
const SOURCES = 'sources/personnages', SORTIE = 'public/modeles/personnages';
const POSE = 'full body, standing straight in A-pose with arms held slightly away from the body, feet apart, facing forward, empty hands, realistic human proportions, photorealistic game character in the style of GTA V, highly detailed face and fabric';
const NEG = 'holding objects, bag, backpack, umbrella, base, pedestal, ground plane, multiple people, cartoon, chibi, big head, toy, arms touching the body, cape';
// Tripo's ready-made animations (biped skeleton v1.0) kept for the game, and their name on the site.
const ANIMS = { idle: 'preset:biped:idle', marche: 'preset:biped:walk', salut: 'preset:biped:greet_01', parle: 'preset:biped:agree', telephone: 'preset:biped:make_a_call_01', assis: 'preset:biped:sit', rire: 'preset:biped:laugh_01' , danse1: 'preset:biped:dance_01', danse2: 'preset:biped:dance_02', acclame: 'preset:biped:cheer' };

// Concert animations, stored separately (see alleger).
const DANSES = ['danse1', 'danse2', 'acclame'];
export const PERSONNAGES = {
  vendeuse: { femme: true, prompt: `A Beninese market woman from Cotonou in her forties, dark brown skin, wearing a long fitted dress in a vivid orange, blue and yellow African wax print (pagne), a matching tied headwrap (foulard), simple flip-flop sandals, ${POSE}` },
  jeune: { femme: false, prompt: `A young Beninese man from Cotonou, about twenty years old, dark skin, short black hair with a fade, wearing a green and yellow football jersey, light blue jeans and white sneakers, slim build, ${POSE}` },
  ancien: { femme: false, prompt: `An elderly Beninese man, about seventy years old, dark skin, short grey beard, wearing a long traditional boubou tunic and trousers in a brown and gold African wax print with embroidery at the neck, a matching kufi cap, leather sandals, ${POSE}` },
  etudiante: { femme: true, prompt: `A young Beninese woman student, about twenty, dark skin, long box braids tied back, wearing a fitted top in a red and black African wax print, dark jeans and white sneakers, ${POSE}` },
  bureau: { femme: false, prompt: `A Beninese office worker man in his thirties, dark skin, short hair, wearing a short-sleeved shirt in a blue and white African wax print tucked into dark grey trousers, black leather shoes, wristwatch, ${POSE}` },
  maman: { femme: true, prompt: `A plump Beninese grandmother in her sixties, dark skin, wearing a loose two-piece outfit (blouse and wrapper skirt) in a green and purple African wax print, a matching headscarf, plastic sandals, ${POSE}` },
  policier: { femme: false, prompt: `A police officer of the Republic of Benin, dark skin, wearing a light blue short-sleeved uniform shirt with epaulettes and badge, dark navy blue trousers, black belt, black boots and a navy blue peaked cap, ${POSE}` },
  'eleve-garcon': { femme: false, enfant: true, prompt: `A Beninese schoolboy about nine years old, dark skin, short black hair, wearing the khaki school uniform of Benin: short-sleeved khaki shirt with pockets and khaki shorts, black plastic sandals, child proportions, ${POSE}` },
  'eleve-fille': { femme: true, enfant: true, prompt: `A Beninese schoolgirl about nine years old, dark skin, hair in short neat braids, wearing the khaki school uniform of Benin: short-sleeved khaki dress with a belt, white socks and black shoes, child proportions, ${POSE}` },
  zem: { femme: false, prompt: `A Beninese zemidjan motorcycle taxi driver from Cotonou, dark skin, wearing a bright yellow short-sleeved work shirt with a black registration number printed on the back and chest, dark trousers, plastic sandals, ${POSE}` },
};

const cle = (() => {
  const l = fs.existsSync('.env.local') ? fs.readFileSync('.env.local', 'utf8').split('\n').find(x => x.startsWith('TRIPO_API_KEY=')) : null;
  return l ? l.slice('TRIPO_API_KEY='.length).trim() : process.env.TRIPO_API_KEY;
})();
async function fetchR(url, opts, essais = 6) {
  for (let k = 0; ; k++) {
    try { return await fetch(url, opts); }
    catch (e) { if (k >= essais - 1) throw new Error(`${e.message} (${e.cause?.code || 'network'}) : ${url.slice(0, 60)}`); await new Promise(r => setTimeout(r, 3000 * (k + 1))); }
  }
}
const api = async (methode, chemin, corps) => {
  if (!cle) throw new Error('TRIPO_API_KEY missing from .env.local');
  const r = await fetchR(BASE + chemin, { method: methode, headers: { Authorization: `Bearer ${cle}`, ...(corps ? { 'Content-Type': 'application/json' } : {}) }, body: corps ? JSON.stringify(corps) : undefined });
  const j = await r.json().catch(() => ({ code: r.status, message: r.statusText }));
  if (j.code !== 0) throw new Error(`Tripo ${chemin} : ${j.code} ${j.message || ''} ${j.suggestion || ''}`.trim());
  return j.data;
};
const solde = async () => { const d = await api('GET', '/account/balance'); return `${d.balance} crédits disponibles`; };

async function attendre(id, etape, task_id) {
  let t, dernier = '';
  for (;;) {
    t = await api('GET', `/tasks/${task_id}`);
    const s = `${id} · ${etape} : ${t.status} ${t.progress ?? 0} %`; if (s !== dernier) { dernier = s; console.log(s); }
    if (t.status === 'success') return t;
    if (['failed', 'cancelled', 'banned', 'expired', 'unknown'].includes(t.status)) throw new Error(`${id} · ${etape}: task ${t.status}`);
    await new Promise(r => setTimeout(r, 5000));
  }
}
const telecharger = async (url, f) => { if (!url) return; const r = await fetchR(url); fs.writeFileSync(f, Buffer.from(await r.arrayBuffer())); };

async function fabriquer(id) {
  const P = PERSONNAGES[id]; if (!P) throw new Error(`personnage inconnu : ${id}`);
  fs.mkdirSync(SOURCES, { recursive: true });
  const fe = `${SOURCES}/${id}.json`, E = fs.existsSync(fe) ? JSON.parse(fs.readFileSync(fe, 'utf8')) : { id, credits: 0 };
  const noter = (k, t) => { E[k] = t.task_id; E.credits += t.credits_consumed || 0; fs.writeFileSync(fe, JSON.stringify(E, null, 2)); };
  // 1. The textured model
  if (!E.modele && !E.modele_en_cours) {
    const { task_id } = await api('POST', '/generation/text-to-model', { prompt: P.prompt, negative_prompt: NEG, model: MODELE, face_limit: 14000, texture: true, pbr: true, texture_quality: 'detailed', texture_version: 'v3.5-20260815', delight: true });
    E.modele_en_cours = task_id; fs.writeFileSync(fe, JSON.stringify(E, null, 2));
  }
  if (!E.modele) { const t = await attendre(id, 'modèle', E.modele_en_cours); noter('modele', t); await telecharger(t.output.rendered_image_url, `${SOURCES}/${id}-apercu.webp`); await telecharger(t.output.model_url || t.output.pbr_model_url, `${SOURCES}/${id}-statique.glb`); }
  // 2. The skeleton
  if (!E.rig) {
    if (!E.rig_en_cours) {
      const chk = await api('POST', '/animations/rig-check', { input: E.modele }); const c = await attendre(id, 'vérification', chk.task_id);
      if (c.output && c.output.riggable === false) throw new Error(`${id} : Tripo juge le modèle impossible à animer (${c.output.rig_type})`);
      const { task_id } = await api('POST', '/animations/rig', { input: E.modele, model: RIG, rig_type: 'biped', spec: 'tripo', out_format: 'glb' });
      E.rig_en_cours = task_id; fs.writeFileSync(fe, JSON.stringify(E, null, 2));
    }
    noter('rig', await attendre(id, 'squelette', E.rig_en_cours));
  }
  // 3. The animations, in place (the game moves the character itself). One request per animation
  // (in a batch, the .glb keeps only one); only the first one carries the mesh, the others
  // contain only the bone motion, merged afterwards into a single file by alleger().
  E.anims ||= {};
  for (const [k, nom] of Object.keys(ANIMS).entries()) {
    const f = `${SOURCES}/${id}-${nom}.glb`; if (fs.existsSync(f)) continue;
    const avecMaillage = k === 0 || !Object.keys(ANIMS).some(n => fs.existsSync(`${SOURCES}/${id}-${n}.glb`));
    if (!E.anims[nom]) {
      const { task_id } = await api('POST', '/animations/retarget', { input: E.rig, animation: ANIMS[nom], out_format: 'glb', bake_animation: true, export_with_geometry: avecMaillage, animate_in_place: true });
      E.anims[nom] = task_id; fs.writeFileSync(fe, JSON.stringify(E, null, 2));
    }
    const t = await attendre(id, `animation ${nom}`, E.anims[nom]);
    E.credits += t.credits_consumed || 0; fs.writeFileSync(fe, JSON.stringify(E, null, 2));
    await telecharger(t.output.model_url, f);
  }
  console.log(`${id} : ${E.credits} credits`);
  await alleger(id);
}

// Lightweight version for the site: 1024 px textures in webp, resampled animations, compressed mesh.
async function alleger(id) {
  await MeshoptDecoder.ready; await MeshoptEncoder.ready;
  const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ 'meshopt.decoder': MeshoptDecoder, 'meshopt.encoder': MeshoptEncoder });
  // The file that carries the mesh is the base; the clips from the others join it (same bones).
  const fichiers = Object.keys(ANIMS).map(nom => [nom, `${SOURCES}/${id}-${nom}.glb`]).filter(([, f]) => fs.existsSync(f));
  const lus = await Promise.all(fichiers.map(async ([nom, f]) => [nom, await io.read(f)]));
  const base = lus.find(([, d]) => d.getRoot().listMeshes().length); if (!base) throw new Error(`${id} : aucun fichier avec le maillage`);
  const doc = base[1], root = doc.getRoot(), buf = root.listBuffers()[0];
  root.listAnimations().forEach(a => a.setName(base[0]));
  const noeuds = new Map(root.listNodes().map(n => [n.getName(), n]));
  for (const [nom, autre] of lus) {
    if (autre === doc) continue;
    for (const a of autre.getRoot().listAnimations()) {
      const na = doc.createAnimation(nom);
      for (const ch of a.listChannels()) {
        const cible = noeuds.get(ch.getTargetNode()?.getName()); if (!cible) continue;
        const s0 = ch.getSampler(), copie = acc => doc.createAccessor().setType(acc.getType()).setArray(acc.getArray().slice()).setBuffer(buf);
        const sp = doc.createAnimationSampler().setInput(copie(s0.getInput())).setOutput(copie(s0.getOutput())).setInterpolation(s0.getInterpolation());
        na.addSampler(sp).addChannel(doc.createAnimationChannel().setTargetNode(cible).setTargetPath(ch.getTargetPath()).setSampler(sp));
      }
    }
  }
  // The concert dances go into a small separate file (<id>-danses.glb: the bones and their motion,
  // with no mesh or texture), downloaded only when you enter the concert.
  const danses = cloneDocument(doc), estDanse = n => DANSES.includes(n);
  // (the internal parts are removed too: otherwise their data stays in the file)
  const jeter = a => { for (const c of a.listChannels()) c.dispose(); for (const sp of a.listSamplers()) sp.dispose(); a.dispose(); };
  for (const a of danses.getRoot().listAnimations()) if (!estDanse(a.getName())) jeter(a);
  for (const n of danses.getRoot().listNodes()) { n.setMesh(null); n.setSkin(null); }
  for (const m of danses.getRoot().listMeshes()) { for (const p of m.listPrimitives()) p.dispose(); m.dispose(); }
  for (const sk of danses.getRoot().listSkins()) sk.dispose();
  for (const a of root.listAnimations()) if (estDanse(a.getName())) jeter(a);
  await danses.transform(resample(), prune({ keepLeaves: true }), meshopt({ encoder: MeshoptEncoder, level: 'medium' }));
  await doc.transform(
    dedup(), resample(), prune(),
    textureCompress({ encoder: sharp, targetFormat: 'webp', resize: [1024, 1024], slots: /baseColor/ }),
    textureCompress({ encoder: sharp, targetFormat: 'webp', resize: [512, 512], slots: /normal|metallicRoughness|occlusion/ }),
    meshopt({ encoder: MeshoptEncoder, level: 'medium' }),
  );
  fs.mkdirSync(SORTIE, { recursive: true });
  const out = `${SORTIE}/${id}.glb`; await io.write(out, doc);
  const outD = `${SORTIE}/${id}-danses.glb`; if (danses.getRoot().listAnimations().length) await io.write(outD, danses);
  const tri = root.listMeshes().flatMap(m => m.listPrimitives()).reduce((s, p) => s + (p.getIndices()?.getCount() ?? 0) / 3, 0);
  const anims = root.listAnimations().map(a => a.getName());
  console.log(`${id}.glb: ${Math.round(tri)} triangles, danses ${fs.existsSync(outD) ? (fs.statSync(outD).size / 1e3).toFixed(0) + ' ko' : '—'}, ${root.listSkins().length} squelette(s), animations [${anims.join(', ')}], ${(fs.statSync(out).size / 1e6).toFixed(2)} Mo`);
  const idx = `${SORTIE}/index.json`, liste = fs.existsSync(idx) ? JSON.parse(fs.readFileSync(idx, 'utf8')) : {};
  liste[id] = { femme: PERSONNAGES[id]?.femme ?? false, enfant: !!PERSONNAGES[id]?.enfant, animations: anims, triangles: Math.round(tri), octets: fs.statSync(out).size, danses: fs.existsSync(outD) ? fs.statSync(outD).size : 0 };
  fs.writeFileSync(idx, JSON.stringify(liste, null, 1));
}

const args = process.argv.slice(2);
try {
  if (args[0] === 'liste') for (const id of Object.keys(PERSONNAGES)) { const f = `${SOURCES}/${id}.json`; console.log(id.padEnd(10), fs.existsSync(`${SORTIE}/${id}.glb`) ? 'prêt' : fs.existsSync(f) ? 'commencé' : '—'); }
  else if (args[0] === 'alleger') await alleger(args[1]);
  else if (args.length) {
    const ids = args[0] === 'tout' ? Object.keys(PERSONNAGES).filter(id => !fs.existsSync(`${SORTIE}/${id}.glb`)) : args;
    console.log(await solde());
    // The characters are built in parallel (each one's steps stay in order).
    const res = await Promise.allSettled(ids.map(fabriquer));
    res.forEach((r, i) => { if (r.status === 'rejected') { console.error(`${ids[i]} : ${r.reason.message}`); process.exitCode = 1; } });
    console.log(await solde());
  } else console.log('Usage : npm run personnages -- liste | tout | <id> [<id>…] | alleger <id>');
} catch (e) { console.error(e.message); process.exitCode = 1; }
