// Places, neighbourhoods and bodies of water shown on the map.
export const KCOL = { hotel: '#b07a3a', savoir: '#e07b39', monument: '#d6452f', marche: '#f2b705', eau: '#2f8fb0', transport: '#5b6bd6', culte: '#8a5cc2', plage: '#e2a35a', institution: '#3d9a6a', quartier: '#c96f3b' };
export const PLACES = [
  { id: 'etoile', name: "Place de l'Étoile Rouge", kind: 'Monument', k: 'monument', lat: 6.37149, lon: 2.40979, h: 52, view: [270, 1.08, 0.7],
    text: "The great crossroads where five roads meet. On the central island, two red stars laid flat, a white spire and, at the very top, a bronze statue of a man carrying a hoe and a sheaf. The monument dates from the mid-1970s, under Mathieu Kérékou." },
  { id: 'dantokpa', name: 'Marché Dantokpa', kind: 'Market', k: 'marche', lat: 6.3727, lon: 2.4352, h: 16, view: [400, 1.05, 2.3],
    text: "Just “Tokpa” to everyone: one of the largest open-air markets in West Africa, on the west bank of the lagoon. Parasols as far as the eye can see, sacks of onions and rice, stalls under corrugated iron and the big building bearing the market's sign." },
  { id: 'amazone', name: "Place de l'Amazone", kind: 'Monument', k: 'monument', lat: 6.34895, lon: 2.40755, h: 36, view: [170, 1.2, 0.15],
    text: "A 30-metre bronze statue unveiled in 2022 in tribute to the Agoodjié, the women warriors of the Kingdom of Dahomey: rifle raised, sabre in hand, on a black stone plinth. The paved esplanade stretches out facing the ocean." },
  { id: 'marina', name: 'Palais de la Marina', kind: 'Presidency', k: 'institution', lat: 6.35163, lon: 2.40908, h: 20, view: [300, 1.05, 2.9],
    text: "Seat of the Presidency of the Republic, along Boulevard de la Marina: a long beige building on pillars, with bluish glazed bands, flags and royal palms." },
  { id: 'congres', name: 'Palais des Congrès', kind: 'Institution', k: 'institution', lat: 6.34775, lon: 2.40501, h: 26, view: [340, 1.02, 3.0],
    text: "Opened in 2003 and inspired by the tata somba of northern Benin: white drums ringed with a frieze of dark triangles, each pierced by a golden oculus, linked by a low wing with claustra screens." },
  { id: 'cathedrale', name: 'Cathédrale Notre-Dame', kind: 'Place of worship', k: 'culte', lat: 6.35637, lon: 2.43917, h: 44, view: [150, 1.15, -1.25],
    text: "The Cathedral of Notre-Dame de Miséricorde (Our Lady of Mercy), in Ganhi, striped red and white from base to gable, with its square bell tower standing beside the nave, a stone's throw from the old bridge." },
  { id: 'port', name: 'Port autonome', kind: 'Port', k: 'transport', lat: 6.3465, lon: 2.4235, h: 30, view: [1100, 0.98, 0.5],
    text: "Benin's main port and the maritime gateway for landlocked countries such as Niger and Burkina Faso. Container gantry cranes along the mole, mobile cranes, ships at berth and large painted pirogues in the fishing port." },
  { id: 'corniche', name: 'Corniche Est', kind: 'Promenade', k: 'plage', lat: 6.3555, lon: 2.4508, h: 10, view: [230, 1.15, 0.6],
    text: "The Corniche Est in Akpakpa: a paved walkway, a brick-coloured jogging track, double-armed street lamps, young coconut palms and groynes of black rock reaching out into the Atlantic." },
  { id: 'aeroport', name: 'Aéroport Cardinal Bernardin Gantin', kind: 'Airport', k: 'transport', lat: 6.35421, lon: 2.38586, h: 18, view: [520, 1.02, 0.35],
    text: "The international airport, right in the city at Cadjèhoun: the terminal with its big yellow sign, the white tents at the entrance, aircraft on the apron and runway 06/24 running along the coast." },
  { id: 'stade', name: "Stade de l'Amitié", kind: 'Stadium', k: 'institution', lat: 6.38614, lon: 2.3794, h: 30, view: [380, 0.95, 0.5],
    text: "The Général Mathieu Kérékou stadium, in Kouhounou, home ground of the national team, the Guépards (Cheetahs): a red running track, yellow, green and red stands, a covered grandstand and lattice floodlight pylons." },
  { id: 'chenal', name: 'Chenal de Cotonou', kind: 'Lagoon', k: 'eau', lat: 6.3665, lon: 2.4405, h: 8, view: [1300, 1.0, 0.9],
    text: "The arm of the lagoon that cuts the city in two and links Lake Nokoué to the ocean. Three bridges span it to reach Akpakpa; pirogues ply along the Dantokpa bank." },
  { id: 'fidjrosse', name: 'Plage de Fidjrossè', kind: 'Beach', k: 'plage', lat: 6.3485, lon: 2.3665, h: 8, view: [300, 1.12, 0.15],
    text: "The western beach, along the Route des Pêches: coconut palms, straw huts, drinks stalls and pirogues pulled up on the sand. The surf here is strong: swimming is dangerous." },
  { id: 'haievive', name: 'Haie Vive', kind: 'Neighbourhood', k: 'quartier', lat: 6.3552, lon: 2.3976, h: 10, view: [380, 1.0, 0.4],
    text: "The neighbourhood of restaurants, bars and maquis (open-air eateries), right next to the airport. Tree-lined streets and terraces under parasols: this is where Cotonou goes out at night." },
  { id: 'nokoue', name: 'Lac Nokoué', kind: 'Lagoon', k: 'eau', lat: 6.432, lon: 2.425, h: 6, view: [3600, 1.08, 0.3],
    text: "The great lagoon north of the city. Fishermen plant acadjas in it, enclosures of branches where fish come to shelter; you can see them as brown lines on the surface of the water." },
  { id: 'bioguera', name: 'Carrefour Bio Guéra', kind: 'Monument', k: 'monument', lat: 6.35015, lon: 2.38752, h: 16, view: [210, 1.05, 0.9],
    text: "At the Erevan crossroads, one of the busiest in Cotonou, stands the equestrian statue of Bio Guéra, a figure of the resistance to French colonisation in the north of the country. Right next to it is the Erevan department store." },
  { id: 'bceao', name: 'Tour BCEAO', kind: 'Architecture', k: 'institution', lat: 6.35333, lon: 2.42639, h: 70, view: [330, 1.05, 0.5],
    text: "The Benin headquarters of the Central Bank of West African States: 64 metres and 16 storeys, the tallest building in Benin, opened in 1994. On each facade, four columns of thirteen golden cowries — the old currency — and five more at the top; in front, a fountain surrounded by seven pools." },
  { id: 'zongo', name: 'Mosquée de Zongo', kind: 'Place of worship', k: 'culte', lat: 6.35680, lon: 2.42637, h: 40, view: [240, 1.08, 0.7],
    text: "The great mosque of the Zongo neighbourhood, in the city centre, with its white minarets towering over the rooftops." },
  { id: 'uac', name: "Université d'Abomey-Calavi", kind: 'Campus', k: 'savoir', lat: 6.4148, lon: 2.3428, h: 16, view: [380, 1.02, 0.6],
    text: "Benin's largest public university, founded in 1970 as the University of Dahomey: the main entrance with its orange pillars, the lecture theatres, the central library and the École polytechnique." },
  { id: 'seme', name: 'Sèmè One', kind: 'Innovation', k: 'savoir', lat: 6.35277, lon: 2.39503, h: 18, view: [190, 1.12, 0.3],
    text: "The first campus of Sèmè City, the international city of innovation and knowledge, opened in 2020 in Les Cocotiers: an ochre facade punctuated by coloured fins. The main campus is under construction in Ouidah." },
  { id: 'calavi', name: 'Abomey-Calavi', kind: 'City', k: 'quartier', lat: 6.4476, lon: 2.3600, h: 12, view: [900, 1.0, 0.9],
    text: "The large neighbouring city, on the shores of Lake Nokoué: the Kpota crossroads, the Calavi-Tokpa market and the landing stage where the pirogues leave for Ganvié." },
  { id: 'ganvie', name: 'Ganvié', kind: 'Lake village', k: 'eau', lat: 6.4681, lon: 2.39, h: 12, view: [240, 1.12, 0.6],
    text: "The stilt village on Lake Nokoué, the “Venice of Africa”. More than five thousand plank houses under corrugated iron or thatch, pirogues everywhere, water hyacinths and a floating market. You get there by pirogue from Abomey-Calavi." },
  { id: 'jardin', name: "Jardin de l'Amazone", kind: 'Public garden', k: 'quartier', lat: 6.35075, lon: 2.40710, h: 22, view: [260, 1.0, 2.6],
    text: "Opposite the Amazone statue, on the other side of Boulevard de la Marina: leaf-shaped lawns, winding paths and a row of sixteen tall tapering pylons along the road. A long promenade leads up to Avenue Jean-Paul II." },
  { id: 'cite', name: 'Cité ministérielle', kind: 'Administration', k: 'institution', lat: 6.35114, lon: 2.40458, h: 26, view: [420, 1.0, 2.7],
    text: "Brought into service in October 2025 on the former site of the Croix du Sud hotel: ten six-level buildings in pale travertine with blue-green ribbon windows, set around planted courtyards and a pool. Sixteen ministries work here; a car-park building houses a thousand-seat restaurant." },
  { id: 'usa', name: 'Ambassade des États-Unis', kind: 'Embassy', k: 'institution', lat: 6.35083, lon: 2.40302, h: 18, view: [260, 1.0, 2.6],
    text: "The American embassy compound, on Boulevard de la Marina, right next to the Cité ministérielle: L-shaped buildings behind a high wall of grey blocks, solar panels over the car parks." },
  { id: 'golden', name: 'Golden Tulip Le Diplomate', kind: 'Hotel', k: 'hotel', lat: 6.34902, lon: 2.40329, h: 22, view: [230, 1.05, 2.9],
    text: "A five-level hotel facing the United States embassy: a white facade with small deep-set windows, a large oxblood-red wall, a grey block and a navy-blue sign with a golden tulip." },
  { id: 'novotel', name: 'Novotel Orisha et Ibis', kind: 'Hotels', k: 'hotel', lat: 6.34880, lon: 2.40120, h: 16, view: [320, 1.0, 2.8],
    text: "Two hotels in the same seven-hectare garden: the V-shaped Novotel Orisha, with grey roofs and blue trim, and the Ibis, a long three-level block with an overhanging red roof. A pond and a small pavilion line the driveway." },
  { id: 'mtn', name: 'Siège de MTN Bénin', kind: 'Company', k: 'institution', lat: 6.34943, lon: 2.39872, h: 34, view: [230, 1.05, 2.5],
    text: "The headquarters of the operator MTN, on Boulevard de la Marina: a building of reflective green glass, a large MTN-yellow panel on the west facade and a red-and-white mast on the roof. Opposite, across the boulevard, stands Nigeria House, the Nigerian embassy." },
  { id: 'dome', name: 'Le Dôme et le Pavillon', kind: 'Sofitel Marina', k: 'hotel', lat: 6.35000, lon: 2.39630, h: 26, view: [280, 1.0, 2.8],
    text: "The former International Conference Centre from 1995, renovated by Sofitel: a large bronze-coloured faceted cone, lit up in the evening. Next door, the Pavillon, with its golden fins and blue glazing, houses two cinema screens, a casino and a club. A walkway of white clouds links them to the hotel." },
  { id: 'superu', name: 'Erevan · Super U', kind: 'Shopping centre', k: 'marche', lat: 6.34895, lon: 2.38694, h: 12, view: [220, 1.05, 3.0],
    text: "The Erevan shopping centre, at the Bio Guéra crossroads: a big burnt-orange box, “SUPER” in blue letters and the U logo, a large car park in front and the “EREVAN” totem by the roadside." },
  { id: 'martyrs', name: 'Place des Martyrs', kind: 'Monument', k: 'monument', lat: 6.35385, lon: 2.40458, h: 12, view: [170, 1.1, 2.6],
    text: "The monument to the martyrs of 16 January 1977: three bronze fighters, one of them a flag-bearer, at the top of a great white staircase lined with stone walls. Since the renovation of Boulevard de la Marina, it stands on a grey granite esplanade lined with flagpoles in Benin's colours." },
  { id: 'ganhi', name: 'Marché Ganhi', kind: 'Market', k: 'marche', lat: 6.35453, lon: 2.43723, h: 10, view: [170, 1.1, 2.3],
    text: "The Ganhi market, rebuilt in 2023 in the heart of the banking district: a long hall on a base of openwork brick, five bays of grey roofs covered with solar panels and a white rosette in the centre. “MARCHE GANHI” stencilled on the walls, motorbikes parked all around." },
  { id: 'murport', name: 'Mur des fresques du port', kind: 'Street art', k: 'monument', lat: 6.35010, lon: 2.41600, h: 8, view: [140, 1.2, 2.9],
    text: "Along the port, on the Boulevard de la Marina side: a kilometre and a half of murals. To the west, “The New Bénin” from the Effet Graff festival (2022); on the former Hôtel du Port, “Coexistence” by the Brazilian artist Eduardo Kobra (2023); then the Marina Boulev'art Gallery, where 27 artists from 13 countries have painted since 2024." },
  { id: 'agl', name: 'Siège d’AGL', kind: 'Logistics', k: 'transport', lat: 6.35085, lon: 2.41977, h: 32, view: [200, 1.05, 2.8],
    text: "The headquarters of Africa Global Logistics (formerly Bolloré), opened in 2017 opposite the port: two blue glass blocks framed in white, six storeys, a wave-shaped canopy in front of the entrance." },
  { id: 'porte', name: 'Porte du Non-Retour', kind: 'Memorial · Ouidah', k: 'monument', lat: 6.32414, lon: 2.08918, h: 16, view: [120, 1.12, 2.75],
    text: "The memorial erected in 1995 on the beach at Ouidah, at the end of the Route des Esclaves (the Slave Route), nearly 4 km from Place Chacha. Its great arch faces the ocean from which the slave ships set sail; its bronze friezes show chained captives marching towards the sea. A site of memory of UNESCO's “Slave Route” project." },
  { id: 'arene', name: 'Arène de Ouidah', kind: 'Arena · Ouidah', k: 'monument', lat: 6.32425, lon: 2.09095, h: 22, view: [260, 0.98, 3.55],
    text: "The seafront arena, a stone's throw from the Porte du Non-Retour (Door of No Return), where the ceremonies and shows of the Vodun Days are held in early January: an ochre sand floor, tiers of red seats under taut white sails, a covered official stand and a forecourt on the town side." },
];
export const QUARTIERS = [
  ['Akpakpa', 6.3712, 2.4600], ['Cadjèhoun', 6.3615, 2.3975], ['Fidjrossè', 6.3555, 2.3690], ['Agla', 6.3760, 2.3680], ['Gbégamey', 6.3640, 2.4130],
  ['Zogbo', 6.3925, 2.3943], ['Ganhi', 6.3530, 2.4385], ['Jonquet', 6.3590, 2.4310], ['Sainte-Rita', 6.3795, 2.4132], ['Mènontin', 6.3885, 2.3736],
  ['Houéyiho', 6.3724, 2.3935], ['Placodji', 6.3505, 2.4320], ['Missèbo', 6.3660, 2.4352], ['Fifadji', 6.3935, 2.4010], ['Vossa', 6.3890, 2.4170],
  ['Ladji', 6.3910, 2.4300], ['Godomey', 6.3870, 2.3420], ['Les Cocotiers', 6.3520, 2.3900], ['Tokplégbé', 6.3660, 2.4905], ['Donaten', 6.3632, 2.4660],
  ['Avotrou', 6.3790, 2.4720], ['Midombo', 6.3790, 2.4430], ['Kouhounou', 6.3830, 2.3830], ['Gbèdjromèdé', 6.3840, 2.4200], ['Aïbatin', 6.3640, 2.3790],
  ['Abomey-Calavi', 6.4500, 2.3520], ['Zogbadjè', 6.4236, 2.3348], ['Togoudo', 6.4071, 2.3345], ['Kpota', 6.4440, 2.3560],
  ['Ouidah', 6.3620, 2.0850], ['Zoungbodji', 6.3405, 2.0889],
];
export const WATER_LABELS = [['Atlantic Ocean', 6.326, 2.40], ['Lagoon', 6.3805, 2.4435]];

